[tool.poetry]
name = "queens-game"
version = "0.1.0"
description = "some fun fun fun"
authors = ["liepieshov"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
